config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :user_infos
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show , :index ,:destroy] do
    resources :likes 
    resources :comments
  end

  resources :user_profiles
  
  resources :users do
    collection do
      get :user_search
      get :user_followed
      get :user_follower
    end
    resources :relationships , only: [:create ]
  end

  resources :relationships , only: [:destroy]

  get "users/:id/user_edit" , to: "users#user_edit" , as: "user_edit" 
  post  "users/:id/user_update" , to: "users#user_update" , as: "user_update"
  get "users/:id/show_user" , to: "users#show_user" , as: "show_user" 
  
  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord

    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'
    
    validates :content, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes , as: :likeable , dependent: :destroy
  validates :comment_text , presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many_attached :post_images , dependent: :destroy
	has_many :likes , as: :likeable , dependent: :destroy
	has_many :comments , dependent: :destroy
	validates :caption , presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User" 
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages , dependent: :destroy
	validates :created_for, :created_by , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many:posts , dependent: :destroy
  has_one:user_info , dependent: :destroy
  has_many :likes ,through: :posts
  has_one :user_profile , dependent: :destroy
  has_many :following  , foreign_key: "follower_id", class_name: "Relationship"
  has_many :followers  , foreign_key: "followed_id", class_name: "Relationship"
  has_many :messages
  validates :name , :user_name , presence: true

  def all_followed(user_id)
    User.find(Relationship.find(user_id).followed_id).name
  end

  def all_follower(user_id)
    User.find(Relationship.find(user_id).follower_id).name
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  validates :bio , presence: true
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  def find_user_profile(user_id)
    return UserProfile.find_by(user_id: user_id).present?
  end

  def find_user_profile_image(user_id)
    return UserProfile.find_by(user_id: user_id).profile_image.present?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = ChatMessage.where(sender_id: current_user.id , receiver_id: 12).order(:created_at)
  end

  def create
    @message = ChatMessage.new(chat_message_params)
    

    if @message.save
      ActionCable.server.broadcast 'chat_channel' ,
      {
        message: @message.content,
        sender: current_user.name,
        receiver_id: @message.receiver_id
      }
    else
      render :index
    end
  end

  private

  def chat_message_params
    params.permit(:content , :receiver_id , :sender_id)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'chats/chat_message', locals: { message: message })
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  def new 
    @like = Like.new
  end

  def create
    if user_signed_in?
      like = @post.likes.create(user_id: current_user.id)
      redirect_to posts_path
    else
      redirect_to user_session_path
    end
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    redirect_to posts_path
  end

	def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def user_edit
    @user = User.find(params[:id])
  end

  def show_user
    @user = User.find(params[:id])
    @user_post = Post.where(user_id: @user.id)
    @user_following = Relationship.where(follower_id:@user.id)
    @user_follower = Relationship.where(followed_id:@user.id)
    @relation_id = @user.followers.find_by(follower: current_user).id if @user.followers.find_by(follower: current_user).present?
    @user_profile_image = UserProfile.find_by(user_id: @user.id).profile_image if UserProfile.find_by(user_id: @user.id).profile_image.attached?
  end

  def user_update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      flash[:success] = "Account updated"
      redirect_back(fallback_location: root_path)
    else
      render :user_edit, status: :unprocessable_entity 
    end
  end

  def user_followed
    @user_relation = Relationship.where(followed_id:current_user.id).present?
    @user_followed = Relationship.where(followed_id:current_user.id)
  end

  def user_follower
    @user_relation = Relationship.where(follower_id:current_user.id).present?
    @user_follower = Relationship.where(follower_id:current_user.id)
  end

  def user_search
    @user_present = User.find_by(name:params[:name]).present?
    @user_search = User.find_by(name: params[:name])
  end
  
  private

  def user_params
    params.permit(:name , :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_allFollowed.html.erb
<p class="d-inline-flex gap-1 ">
  <p class="" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Followed
  </p>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body" >
    <table class="table" >    
      <tbody>
        <% user_following.each do |user| %>
          <tr>
            <td><%= User.new.all_followed(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_allFollower.html.erb
<p class="d-inline-flex gap-1">
  <p class=" ms-1" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample1">
    Followers
  </p>
</p>
<!-- First collapsible section -->
<div class="collapse" id="collapseExample1">
  <div class="card card-body">
    <table class="table">
      <tbody>
        <% user_follower.each do |user| %>
          <tr>
            <td><%= User.new.all_follower(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<html>
  <head>
    <style>
      .user_profile{
        position:relative;
        top:70px;
        width:800px;
        margin-left:237px;}
    </style>
  </head>
  <body>
  <div class="user_profile bg-white">
    <div class="p-3 d-flex">
      <%= image_tag url_for(UserProfile.find_by(user_id: @user.id).profile_image) ,style:"width:100px; height:100px ; border-radius:180px " if UserProfile.find_by(user_id: @user.id).profile_image.attached? %> 
      <div class="ms-3">
        <%= button_to "Follow", user_relationships_path(@user), method: :post, class: "btn btn-primary", form: { data: { turbo: false } } unless @user.followers.find_by(follower: current_user).present? %>
        <%= button_to "Unfollow" , relationship_path(@user.followers.find_by(follower: current_user).id) , method: :delete , class:"btn btn-primary" if @user.followers.find_by(follower: current_user).present? %>
      </div> 
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="pb-4">Name</th>
          <th scope="col" class="pb-4">User_name</th>
          <th scope="col"><%= render "allFollower" , user_follower: @user_follower %> </th>
          <th scope="col"><%= render "allFollowed" , user_following: @user_following %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.name %></td>
          <td><%= @user.user_name %></td>
          <td><%= @user.following.count %>  </td>
          <td><%= @user.followers.count %>  </td>
        </tr>
      </tbody>
    </table>

    <div class="row p-4">
      <% @user_post.each do |user_post| %>
      <div class="card" style="width: 16rem;">
        <% if user_post.post_images.attached? %>
        <a href="/posts/<%= user_post.id %> ">
          <%= image_tag main_app.rails_blob_url(user_post&.post_images&.attachments&.first) , class:"card-img-top"  if user_post.post_images.attached? %>
        </a>
          <div class="card-body">
            <p>Likes:- <%= user_post.likes.count %>  </p>
            <p>Comments:- <%= user_post.comments.count %> </p>
            <p class="card-text"><%= user_post.caption %></p> 
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  </body>
</html>

app/views/users/show_user.html.erb
<html>
  <head>
    <style>
      .user_profile{
        position:relative;
        top:70px;
        width:800px;
        margin-left:237px;}
    </style>
  </head>
  <body>
  <div class="user_profile bg-white">
    <div class="p-3 d-flex">
      <%= image_tag url_for(@user_profile_image) ,style:"width:100px; height:100px ; border-radius:180px " if @user_profile_image %> 
      <div class="ms-3">
        <%= button_to "Follow", user_relationships_path(@user), method: :post, class: "btn btn-primary", form: { data: { turbo: false } } unless @user.followers.find_by(follower: current_user).present? %>
        <%= button_to "Unfollow" , relationship_path(@relation_id) , method: :delete , class:"btn btn-primary"  if @relation_id %>
      </div> 
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="pb-4">Name</th>
          <th scope="col" class="pb-4">User_name</th>
          <th scope="col"><%= render "allFollower" , user_follower: @user_follower %> </th>
          <th scope="col"><%= render "allFollowed" , user_following: @user_following %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.name %></td>
          <td><%= @user.user_name %></td>
          <td><%= @user.followers.count %>  </td>
          <td><%= @user.following.count %>  </td>
        </tr>
      </tbody>
    </table>

    <div class="row p-4">
      <% @user_post.each do |user_post| %>
      <div class="card" style="width: 16rem;">
        <% if user_post.post_images.attached? %>
        <a href="/posts/<%= user_post.id %> ">
          <%= image_tag main_app.rails_blob_url(user_post&.post_images&.attachments&.first) , class:"card-img-top"  if user_post.post_images.attached? %>
        </a>
          <div class="card-body">
            <p>Likes:- <%= user_post.likes.count %>  </p>
            <p>Comments:- <%= user_post.comments.count %> </p>
            <p class="card-text"><%= user_post.caption %></p> 
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  </body>
</html>

app/views/users/user_edit.html.erb
<!DOCTYPE html>
<html >
  <head>
    <style>
      .edit_details{
        position: relative;
        top:150px;}
    </style>
  </head>
<body>
  <div class="edit_details">
    <div class="card" style="width:400px;  margin-left:400px">
      <div style="margin-left:85%">
        <%= link_to 'Back', posts_path, class:"btn btn-outline-success" %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= current_user.name%></h5>
        <%= form_with(url: user_update_path(@user.id) , method: :post ) do |form| %>
        <div>
          <%= form.label :name, "Edit your name:" %>
        </div>
          <%= form.text_field :name %>
        <div>
          <%= form.label :user_name, "Edit your user_name:" %> 
        </div>
          <%= form.text_field :user_name %>
          <br>
          <button class="btn btn-outline-success mt-2" >Done</button>
      </div>
        <% end %>
    </div>
  </div>
</body>
</html>




 

app/views/users/user_followed.html.erb
<%len = @user_followed.length %>
<% if @user_relation %>
  <div class="card" style="height: 500px; width: 700px; background-color: #ede4e4; position:relative; left:290px; top:100px;">
    <div>        
      <% for i in 0...len do %>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Name:</td>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: right"><%= User.find(@user_followed[i].follower_id).name %></td>
          </tr>
        </table>
      <% end %>
        <td style="padding: 10px; border: 1px solid #ccc;"><%= link_to 'Back', posts_path, class:"btn btn-outline-success" %></td>
    </div>
  </div>
<% end %>

app/views/users/user_follower.html.erb
<%len = @user_follower.length %>
<% if @user_relation %>
  <div class="card" style="height: 500px; width: 700px; background-color: #ede4e4; position:relative; left:290px; top:100px;">
    <div>        
      <% for i in 0...len do %>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Name:</td>
            <td style="padding: 10px; border: 1px solid #ccc; text-align: right"><%= User.find(@user_follower[i].followed_id).name %></td>
          </tr>
        </table>
      <% end %>
        <td style="padding: 10px; border: 1px solid #ccc;"><%= link_to 'Back', posts_path, class:"btn btn-outline-success" %></td>
    </div>
  </div>
<% end %>

app/views/users/user_search.html.erb
<!DOCTYPE html>
<html >
  <head>
    <style>
      .user_pro{
      position:relative;
      left:300px;
      top:100px}
      .card:hover{
        box-shadow: 10px 10px 20px 10px grey ;
        border-radius:10px;
    </style>
  </head>
  <body> 
    <div class="user_pro">
      <div class="card" style="height: 500px; width: 700px; background-color: #ede4e4;">
        <% if @user_present %>
          <div style="text-align: center; margin-top: 30px;">
            <% if UserProfile.find_by(user_id: @user_search).present? %>
              <% if UserProfile.find_by(user_id: @user_search.id).profile_image.present? %>
              <a href="<%= show_user_path(@user_search.id) %> " >
                <%= image_tag (UserProfile.find_by(user_id:@user_search.id).profile_image&.attachments&.first  if UserProfile.find_by(user_id: @user_search.id).profile_image.attached? ) , style:"width:100px; height:100px ; border-radius:180px " %> 
              </a>
              <% end %>
            <% end %>
          </div>
          <div style="margin: 20px;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Name:</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= @user_search.name %></td>
              </tr>
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Username:</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= @user_search.user_name %></td>
              </tr>
                <% if UserInfo.find_by(user_id: @user_search.id).present? %>
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Bio:</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= @user_search.user_info.bio %></td>
              </tr>
                <% end %>
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Followers:</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= @user_search.followers.count %></td>
              </tr>
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;">Following:</td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= @user_search.following.count %></td>
              </tr>
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc; text-align: left;"><%= button_to "Follow", user_relationships_path(User.find_by(id: @user_search.id)), method: :post, class: "btn btn-danger", form: { data: { turbo: false } } unless User.find_by(id:@user_search.id).followers.find_by(follower: current_user).present? %></td>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= button_to "unfollow" , relationship_path(User.find_by(id: @user_search.id).followers.find_by(follower: current_user).id) , method: :delete , class:"btn btn-danger" if User.find_by(id:@user_search.id).followers.find_by(follower: current_user).present? %></td>
              </tr> 
              <tr>
                <td style="padding: 10px; border: 1px solid #ccc;"><%= link_to 'Back', posts_path, class:"btn btn-outline-success" %></td>
              </tr>
            </table>
          </div>
        <% else %>
          <table>
            <tr>
              <td style="padding: 10px; border: 1px solid #ccc; text-align: center;">Please Enter correct name </td>
              <td style="padding: 10px; border: 1px solid #ccc;"><%= link_to 'Back', posts_path, class:"btn btn-outline-success" %></td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </body>
</html>       