config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :user_infos
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show , :index ,:destroy] do
    resources :likes 
    resources :comments
  end

  resources :user_profiles
  
  resources :users do
    collection do
      get :user_search
      get :user_followed
      get :user_follower
    end
    resources :relationships , only: [:create ]
  end

  resources :relationships , only: [:destroy]

  get "users/:id/user_edit" , to: "users#user_edit" , as: "user_edit" 
  post  "users/:id/user_update" , to: "users#user_update" , as: "user_update"
  get "users/:id/show_user" , to: "users#show_user" , as: "show_user" 
  
  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord

    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'
    
    validates :content, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes , as: :likeable , dependent: :destroy
  validates :comment_text , presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many_attached :post_images , dependent: :destroy
	has_many :likes , as: :likeable , dependent: :destroy
	has_many :comments , dependent: :destroy
	validates :caption , presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User" 
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages , dependent: :destroy
	validates :created_for, :created_by , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many:posts , dependent: :destroy
  has_one:user_info , dependent: :destroy
  has_many :likes ,through: :posts
  has_one :user_profile , dependent: :destroy
  has_many :following  , foreign_key: "follower_id", class_name: "Relationship"
  has_many :followers  , foreign_key: "followed_id", class_name: "Relationship"
  has_many :messages
  validates :name , :user_name , presence: true

  def all_followed(user_id)
    User.find(Relationship.find(user_id).followed_id).name
  end

  def all_follower(user_id)
    User.find(Relationship.find(user_id).follower_id).name
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  validates :bio , presence: true
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  def find_user_profile(user_id)
    return UserProfile.find_by(user_id: user_id).present?
  end

  def find_user_profile_image(user_id)
    return UserProfile.find_by(user_id: user_id).profile_image.present?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = ChatMessage.where(sender_id: current_user.id , receiver_id: 12).order(:created_at)
  end

  def create
    @message = ChatMessage.new(chat_message_params)
    

    if @message.save
      ActionCable.server.broadcast 'chat_channel' ,
      {
        message: @message.content,
        sender: current_user.name,
        receiver_id: @message.receiver_id
      }
    else
      render :index
    end
  end

  private

  def chat_message_params
    params.permit(:content , :receiver_id , :sender_id)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'chats/chat_message', locals: { message: message })
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
    def new
      @user_profile = UserProfile.new
    end
    
    def show
      @user_profile = UserProfile.find(params[:id])
    end
    
    def create
      if user_signed_in?
        user_profile = current_user.create_user_profile(user_profile_params)
        user_profile.profile_image.attach(params[:profile_image])
        
        if user_profile.save!
          redirect_to posts_path
        else
          render :new, notice: "Image succesfully created"
        end
      else
        redirect_to user_session_path
      end
    end

    def edit 
      @user_profile = UserProfile.find_by(id: params[:id])
    end

    def update
      user_profile = UserProfile.find(params[:id])
      if user_profile.update(user_profile_params)
        redirect_to posts_path
      end
    end

    private

    def user_profile_params
      params.permit(:profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_profiles/_userprofile.html.erb
<html>
  <head>
  </head>
  <body>
    <div class="card" , style="height:700px ; width:215px ; background-color:white;">
      <div style="text-align:center ; margin-top:30px">
        <div>
          <% if UserProfile.new.find_user_profile(current_user.id) %> 
            <% if UserProfile.new.find_user_profile_image(current_user.id) %>
              <a href="<%= show_user_path(current_user.id) %> " >
                <%= image_tag (UserProfile.find_by(user_id:current_user).profile_image&.attachments&.first  if UserProfile.find_by(user_id:current_user).profile_image.attached? ) , style:"width:100px; height:100px ; border-radius:180px " %> 
              </a>
            <% end %>
            <div>
              <%= link_to "..." ,  edit_user_profile_path(UserProfile.find_by(user_id:current_user))  %>
            </div>
          <% else %>
            <%= link_to "Upload profile" , new_user_profile_path %>
          <% end %>
        </div>
        <div class="mt-3" >
          <table class="table table-bordered"  >
            <tbody>
              <tr>
                <td>Name</td>
                <td>
                  <%= link_to "#{current_user.name}", user_edit_path(current_user.id) , class:"nav-link"  %>
                </td>
              </tr>
              <tr>
                <td>User Name</td>
                <td><%= current_user.user_name %></td>
              </tr>
              <% if UserInfo.find_by(user_id: current_user.id).present? %>
                <tr>
                  <td>Bio</td>
                  <td>
                    <%= link_to "#{current_user.user_info.bio}", edit_user_info_path(current_user.user_info.id)  , class:"nav-link"%>
                  </td>
                </tr>
              <% else %>
                <tr>
                  <td colspan="2">
                    <%= link_to "Create Bio", new_user_info_path, class: "btn btn-outline-success", style: "width:60px; height:28px" %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td>Followers</td>
                <td>
                  <%= link_to "#{current_user.followers.count}", user_followed_users_path, class:"nav-link"  %>
                </td>
              </tr>
              <tr>
                <td>Followed</td>
                <td>
                  <%= link_to "#{current_user.following.count}", user_follower_users_path, class:"nav-link" %>
                </td>
              </tr>
              <tr>
              <td>Chat</td>
              <td>
                <a href="<%= rooms_path %>" >
                  <img src="https://static.vecteezy.com/system/resources/thumbnails/006/692/724/small_2x/chatting-message-icon-template-black-color-editable-chatting-message-icon-symbol-flat-illustration-for-graphic-and-web-design-free-vector.jpg" , style="width:40px ; height:40px"  >
                </a>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>  
    </div>
  </body>
</html>

app/views/user_profiles/edit.html.erb
<html >
  <head>
    <style>
      .box:hover{
        box-shadow: 10px 10px 20px 10px grey ;
        border-radius:10px;}
      
        .box{
          position:relative;
          top:100px;
        }

    </style> 
  </head>
<body>
  <div style="width:850px" class="box , container" >
    <div class="container , bg-body-secondary">
      <div style="margin-left:94%">
        <%= link_to 'Back', posts_path, class:"btn btn-outline-success" %>
      </div>
      <%= form_with(url: user_profile_path(@user_profile) , method: :put) do |form| %>
      <div class="form-group , mt-5">
        <%= form.label :profile_image, 'Upload Image' %>
          <div class="mt-3"> 
            <%= form.file_field :profile_image, class: 'form-control' %>
          </div>
      </div>
      <div class="form-group mt-4 , text-center">
        <%= form.submit 'Upload profile', class:"btn btn-outline-success" %>
      </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/user_profiles/new.html.erb
<html >
  <head>
    <style>
      .box:hover{
        box-shadow: 10px 10px 20px 10px grey ;
        border-radius:10px;}
    </style> 
  </head>
<body>
  <div style="width:1300px" class="box , container" >
    <div style="margin-top:8%" class="container , bg-body-secondary">
      <div style="margin-left:95.5%">
        <%= link_to 'Back', posts_path, class:"btn btn-outline-success" %>
      </div>
      <%= form_with(url: user_profiles_path) do |form| %>
      <div class="form-group , mt-5">
        <%= form.label :profile_image, 'Upload Image' %>
          <div class="mt-3"> 
            <%= form.file_field :profile_image, class: 'form-control' %>
          </div>
      </div>
      <div class="form-group mt-4 , text-center">
        <%= form.submit 'Upload profile', class:"btn btn-outline-success" %>
      </div>
      <% end %>
    </div>
  </div>
</body>
</html>