config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :user_infos
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show , :index ,:destroy] do
    resources :likes 
    resources :comments
  end

  resources :user_profiles
  
  resources :users do
    collection do
      get :user_search
      get :user_followed
      get :user_follower
    end
    resources :relationships , only: [:create ]
  end

  resources :relationships , only: [:destroy]

  get "users/:id/user_edit" , to: "users#user_edit" , as: "user_edit" 
  post  "users/:id/user_update" , to: "users#user_update" , as: "user_update"
  get "users/:id/show_user" , to: "users#show_user" , as: "show_user" 
  
  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord

    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'
    
    validates :content, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes , as: :likeable , dependent: :destroy
  validates :comment_text , presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many_attached :post_images , dependent: :destroy
	has_many :likes , as: :likeable , dependent: :destroy
	has_many :comments , dependent: :destroy
	validates :caption , presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User" 
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages , dependent: :destroy
	validates :created_for, :created_by , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many:posts , dependent: :destroy
  has_one:user_info , dependent: :destroy
  has_many :likes ,through: :posts
  has_one :user_profile , dependent: :destroy
  has_many :following  , foreign_key: "follower_id", class_name: "Relationship"
  has_many :followers  , foreign_key: "followed_id", class_name: "Relationship"
  has_many :messages
  validates :name , :user_name , presence: true

  def all_followed(user_id)
    User.find(Relationship.find(user_id).followed_id).name
  end

  def all_follower(user_id)
    User.find(Relationship.find(user_id).follower_id).name
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  validates :bio , presence: true
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  def find_user_profile(user_id)
    return UserProfile.find_by(user_id: user_id).present?
  end

  def find_user_profile_image(user_id)
    return UserProfile.find_by(user_id: user_id).profile_image.present?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = ChatMessage.where(sender_id: current_user.id , receiver_id: 12).order(:created_at)
  end

  def create
    @message = ChatMessage.new(chat_message_params)
    

    if @message.save
      ActionCable.server.broadcast 'chat_channel' ,
      {
        message: @message.content,
        sender: current_user.name,
        receiver_id: @message.receiver_id
      }
    else
      render :index
    end
  end

  private

  def chat_message_params
    params.permit(:content , :receiver_id , :sender_id)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'chats/chat_message', locals: { message: message })
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  def new 
    @like = Like.new
  end

  def create
    if user_signed_in?
      like = @post.likes.create(user_id: current_user.id)
      redirect_to posts_path
    else
      redirect_to user_session_path
    end
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    redirect_to posts_path
  end

	def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    room = Room.new(room_params)
    if room.save
      redirect_to rooms_path
    end
  end

  def update
    @room.update(room_params)
  end

  def destroy
    if @room.destroy!
      redirect_to rooms_path
    end
  end

  private

  def set_room
    @room = Room.find(params[:id]) 
  end

  def room_params
    params.require(:room).permit(:name , :created_by , :created_for )
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :created_by , value: current_user.id %>
    <%= form.select :created_for, options_from_collection_for_select(User.all, :id, :name), { include_blank: 'Select Friend' }, { class: "form-controller btn btn-outline-success btn-sm mt-2" } %>
    <%= form.submit "AddFriend" , class: "btn btn-outline-success btn-sm mt-2" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<html>
  <head>
    <style>
      .chat{
        width:360px;
        position: relative;
        top:100px;
        left:400px;}
        
      .chat:hover{
        box-shadow: 10px 10px 20px 10px grey ;
        border-radius:10px;
        border:1px solid green;}
    </style>
  </head>
  <body>
    <div class="chat , card">
      <div class="conatainer-fluid">
        <div class="row">
          <div class="col-9">
            <div class="ms-5 mt-2"><%= render 'form' ,  room: Room.new %></div>
              <div class="mt-5 ms-5">
                <h5>Chat List</h5>
                <% if Room.any? %>
                  <table class="table">
                    <tbody>
                      <% @rooms.each do |room| %>
                        <% if (room.created_by == current_user.id) %>
                          <tr>
                            <td> 
                              <a href="<%= show_user_path(User.find(room.created_for).id) %> " >
                                <%= image_tag main_app.rails_blob_url(UserProfile.find_by(user_id: User.find(room.created_for).id ).profile_image.attachments&.first), style: "width:35px; height:35px; border-radius:100px" %>
                              </a>
                            </td>
                            <td>
                              <%= link_to "#{User.find(room.created_for).name}", room_path(room.id), class: "nav-link" %>
                            </td>
                            <td>
                              <%= link_to "Remove", room_path(room.id),  data: { turbo_method: :delete , turbo_confirm: "Are you sure?" }, class: "nav-link" %>
                            </td>
                          </tr>
                        <% elsif (room.created_for == current_user.id) %>
                          <tr>
                            <td>
                              <a href="<%= show_user_path(User.find(room.created_by).id) %> " >
                                <%= image_tag main_app.rails_blob_url(UserProfile.find_by(user_id: User.find(room.created_by).id ).profile_image.attachments&.first), style: "width:35px; height:35px; border-radius:100px" %>
                              </a>
                            </td>
                            <td>
                              <%= link_to "#{User.find(room.created_by).name}", room_path(room.id), class: "nav-link" %>
                            </td>
                            <td>
                              <%= link_to "Remove", room_path(room.id),  data: { turbo_method: :delete ,  turbo_confirm: "Are you sure?" }, class: "nav-link" %>
                            </td>
                          </tr>
                        <% end %>
                      <% end %>
                    </tbody>
                  </table>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rooms/new.html.erb
<div style="margin:400px">
  <h1>New room</h1>
  <%= render "form", room: @room %>
  <br>
  <div>
    <%= link_to "Back to rooms", rooms_path %>
  </div>
</div>

app/views/rooms/show.html.erb
<html>
  <head>
    <style>
      .chat{
        width:400px;
        position: relative;
        top:100px;
        left:400px; }

        .messages-container {
          max-height:350px; 
          overflow-y: auto; 
          padding: 3px; 
          border: 1px solid #ddd; 
          background-color: #f9f9f9; 
        }

        .chat:hover{
          box-shadow: 10px 10px 20px 10px grey ;
          border:1px solid green;}

    </style>
  </head>
  <body>
    <div class="chat , card ">
      <div class="conatainer-fluid">
        <div class="row">
          <div class="col-12">
            <% if @room.created_by == current_user.id %>
              <p class="divider py-1 bg-secondary text-light">
                <a href="<%= show_user_path(User.find(@room.created_for).id) %> " >
                  <%= image_tag main_app.rails_blob_url(UserProfile.find_by(user_id: User.find(@room.created_for).id ).profile_image.attachments&.first), style: "width:25px; height:25px; border-radius:100px" %>
                </a>
                <%= User.find(@room.created_for).name %> <%= link_to "...", rooms_path %> 
              </p>
              
              <div class="messages-container" , style="height:400px">
              <% @room.messages.each do |message| %>
                <% if current_user.id == User.find(message.user_id).id %>
                <div class="text-end , me-3" > 
                  <%= link_to "#{message.content}" , message_path(message.id) , data: { turbo_method: :delete , turbo_confirm: "Are you sure?" }, class: "nav-link" %>
                  <p style="font-size:12px" class="text-muted" ><%= User.find(message.user_id).name %></p>
                </div>
                <% else %>
                  <div class= "ms-2">  
                    <%= message.content %>
                    <p style="font-size:12px" class="text-muted" ><%= User.find(message.user_id).name %></p>
                  </div>
                <% end %>
              <% end %>
              </div>
              <div>
                <%= render 'messages/form' , message: Message.new , room: @room , user: current_user.id%>
              </div> 

            <% elsif (@room.created_for == current_user.id) %>
              <p class="divider py-1 bg-secondary text-light" >
                <a href="<%= show_user_path(User.find(@room.created_by).id) %> " >
                  <%= image_tag main_app.rails_blob_url(UserProfile.find_by(user_id: User.find(@room.created_by).id ).profile_image.attachments&.first), style: "width:25px; height:25px; border-radius:100px" %>
                </a>
                <%= User.find(@room.created_by).name %> <%= link_to "...", rooms_path %>
              </p>
              <div class="messages-container" , style="height:400px">
              <% @room.messages.each do |message| %>
                <% if current_user.id == User.find(message.user_id).id %>
                <div class="text-end me-3"> 
                  <%= link_to "#{message.content}" , message_path(message.id) , data: { turbo_method: :delete , turbo_confirm: "Are you sure?" }, class: "nav-link" %>
                  <p style="font-size:12px" , class="text-muted" ><%= User.find(message.user_id).name %></p>
                </div>
                <% else %>
                <div class= "ms-2">  
                  <%= message.content %>
                  <p style="font-size:12px" class="text-muted" ><%= User.find(message.user_id).name %></p>
                </div>
                <% end %>
              <% end %>
              </div>
              <div>
                <%= render 'messages/form' , message: Message.new , room: @room , user: current_user.id%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>