config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :user_infos
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show , :index ,:destroy] do
    resources :likes 
    resources :comments
  end

  resources :user_profiles
  
  resources :users do
    collection do
      get :user_search
      get :user_followed
      get :user_follower
    end
    resources :relationships , only: [:create ]
  end

  resources :relationships , only: [:destroy]

  get "users/:id/user_edit" , to: "users#user_edit" , as: "user_edit" 
  post  "users/:id/user_update" , to: "users#user_update" , as: "user_update"
  get "users/:id/show_user" , to: "users#show_user" , as: "show_user" 
  
  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord

    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'
    
    validates :content, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes , as: :likeable , dependent: :destroy
  validates :comment_text , presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many_attached :post_images , dependent: :destroy
	has_many :likes , as: :likeable , dependent: :destroy
	has_many :comments , dependent: :destroy
	validates :caption , presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User" 
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages , dependent: :destroy
	validates :created_for, :created_by , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many:posts , dependent: :destroy
  has_one:user_info , dependent: :destroy
  has_many :likes ,through: :posts
  has_one :user_profile , dependent: :destroy
  has_many :following  , foreign_key: "follower_id", class_name: "Relationship"
  has_many :followers  , foreign_key: "followed_id", class_name: "Relationship"
  has_many :messages
  validates :name , :user_name , presence: true

  def all_followed(user_id)
    User.find(Relationship.find(user_id).followed_id).name
  end

  def all_follower(user_id)
    User.find(Relationship.find(user_id).follower_id).name
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
  validates :bio , presence: true
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  def find_user_profile(user_id)
    return UserProfile.find_by(user_id: user_id).present?
  end

  def find_user_profile_image(user_id)
    return UserProfile.find_by(user_id: user_id).profile_image.present?
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = ChatMessage.where(sender_id: current_user.id , receiver_id: 12).order(:created_at)
  end

  def create
    @message = ChatMessage.new(chat_message_params)
    

    if @message.save
      ActionCable.server.broadcast 'chat_channel' ,
      {
        message: @message.content,
        sender: current_user.name,
        receiver_id: @message.receiver_id
      }
    else
      render :index
    end
  end

  private

  def chat_message_params
    params.permit(:content , :receiver_id , :sender_id)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'chats/chat_message', locals: { message: message })
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  def new 
    @like = Like.new
  end

  def create
    if user_signed_in?
      like = @post.likes.create(user_id: current_user.id)
      redirect_to posts_path
    else
      redirect_to user_session_path
    end
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy
    redirect_to posts_path
  end

	def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    if user_signed_in?
      post = current_user.posts.new(post_params)
      post.post_images.attach(params[:post][:post_images])
      if post.save!
        PostConfirmationMailer.with(user: current_user).post_confirmation_mailer.deliver_later
        redirect_to post
      else
        render :new, notice: "Image succesfully created"
      end
    else
      redirect_to user_session_path
    end
  end

  def destroy
    if user_signed_in?
      post = Post.find(params[:id])
      post.destroy
      redirect_to posts_path
    else
      redirect_to user_session_path
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:post_images, :caption, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_allLikes.html.erb
<p class="d-inline-flex gap-1 ">
  <button class="btn btn-outline-success ms-1 " type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <%= Post.find(post.id).likes.count %>
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body" >
    <table class="table" >    
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        <% post.likes.each do |like| %>
          <tr>
            <td><%= User.find(like.user_id).name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/_allcomment.html.erb
<p class="d-inline-flex gap-1">
  <button class="btn btn-outline-success ms-1" type="button" data-bs-toggle="collapse" data-bs-target="#collapseComments" aria-expanded="false" aria-controls="collapseComments">
    All comments
  </button>
</p>
<div class="collapse" id="collapseComments">
  <div class="card card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Comment</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% post.comments.each do |comment| %>
          <tr>
            <td><%= User.find(comment.user_id).name %></td>
            <td><%= comment.comment_text %></td>
            <td>
              <% if user_signed_in? && current_user.id == comment.user_id %>
                <%= link_to "Delete", post_comment_path(post_id: comment.post_id, id: comment.id), class: "btn btn-outline-success btn-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/posts/_postcard.html.erb
<% @posts.each do |p| %>
  <div class="card mb-3 bg-info-subtle" , style="border-radius:20px; width:850px ">
    <% if p.post_images.present? %>
      <div>
        <div class="d-flex p-1 divider py-1 bg-secondary text-light  rounded-3 ">  
          <div>      
            <a href="<%= show_user_path(current_user.id) if user_signed_in? %> " >
              <%= image_tag main_app.rails_blob_url(UserProfile.find_by(user_id: p.user_id).profile_image.attachments&.first), style: "width:40px; height:40px; border-radius:100px" %>
            </a>
          </div>
          <h6 style="float:left ; margin:10px"><%= User.find_by(id: p.user_id).name %></h6>
          <%= button_to "Follow", user_relationships_path(User.find_by(id: p.user_id)), method: :post, class: "btn btn-primary", form: { data: { turbo: false } } unless User.find_by(id: p.user_id).followers.find_by(follower: current_user).present? %>
          <%= button_to "Unfollow" , relationship_path(User.find_by(id: p.user_id).followers.find_by(follower: current_user).id) , method: :delete , class:"btn btn-primary" if User.find_by(id: p.user_id).followers.find_by(follower: current_user).present? %>
          <div style="margin-left:64%">
            <% if user_signed_in? %>
            <% if p.user_id == current_user.id %>
            <%= link_to "delete" , post_path(p.id) , class:"btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
            <% end %>
            <% end %>
          </div>
        </div>
        <%= image_tag main_app.rails_blob_url(p&.post_images&.first&.attachments&.first), style: "max-width: 100%; border-radius:10px" %>
        <p><%= p.caption %></p>
        <!-- like button -->
        <div style="display:inline; display:flex; margin-bottom:15px">
          <% if user_signed_in? %>
            <% if Like.where(user_id: current_user.id , likeable_id: p.id ).present? %> 
            <%= link_to "Unlike", post_like_path(post_id:p.id , id:Like.find_by(user_id: current_user.id , likeable_id: p.id ).id ) , class: "btn btn-outline-success btn-sm", style:"height:38px" , data: { turbo_method: :delete } %>
            <div>
              <%= render "posts/allLikes", post: p %>
            </div>

            <% else %>
              <%= form_with(url: post_likes_path(p)) do %>
              <button class="btn btn-outline-success"> <%= Like %> </button>
            <% end %>
            <div>
              <%= render "posts/allLikes", post: p %>
            </div>
          <% end %>
          <% end %> 
          <div>
            <%= link_to "Create Comment", new_post_comment_path(p), class: "btn btn-outline-success ms-1" %>
          </div> 
          <div>
            <%= render "posts/allcomment", post: p %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/create.html.erb
<!-- app/views/posts/create.html.erb -->
<%= form_with(model: @post, local: true, html: { multipart: true }) do |form| %>
  <div class="form-group">
    <%= form.label :post_images, 'Upload Image' %>
    <%= form.file_field :post_images, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :caption, 'Caption' %>
    <%= form.text_area :caption, class: 'form-control', rows: 3 %>
  </div>

  <div class="form-group">
    <%= form.submit 'Create Image Post', class: 'btn btn-primary' %>
  </div>
<% end %>

<!-- Display error messages -->
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(@post.errors.count, "error") %> prohibited this image post from being saved:</h4>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/index.html.erb
<html>

<head>
<style>
.post{
  position:relative;
  top:57px;
}
</style>

</head>

<body>
<div class="post" , style=" margin-left:215px;">
  <%= render "postcard" %>
</div>
</body>
</html>

app/views/posts/new.html.erb
<html lang="en">
  <head>
    <style>
      .box:hover{
        box-shadow: 10px 10px 20px 10px grey ;
        border-radius:10px;}
      .box{
        position: relative;
        top:58px;
        left:214px;}
    </style> 
  </head>
  <body>
    <div style="width:865px;" , class="box " >
      <div  class="container , bg-body-secondary">
        <div style="margin-left:94%">
          <%= link_to 'Back', posts_path, class:"btn btn-outline-success" %>
        </div>
        <%= form_with(model: @post, local: true, html: { multipart: true }) do |form| %>
        <div class="form-group , mt-5">
        <%= form.label :post_images, 'Upload Image' %>
        <div class="mt-3">
          <%= form.file_field :post_images, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group , mt-3">
        <%= form.label :caption, 'Caption' %>
        <div class="mt-3">
          <%= form.text_area :caption, class: 'form-control', rows: 3 %>
        </div>
      </div>

      <div class="form-group mt-4 , text-center">
        <%= form.submit 'Create Post', class:"btn btn-outline-success" %>
      </div>
      <% end %>
      </div>
    </div>
  </body>
</html>

app/views/posts/show.html.erb
<!-- app/views/image_posts/show.html.erb -->
<div style="margin-left:50%"><%= link_to 'Delete Post', post_path(@post), data: {  
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"} ,  class: 'btn btn-secondary'  %>
  <%= link_to 'see all post', posts_path, class: 'btn btn-secondary' %>
</div>

<div class="container col-8">
  <div class="row">
    <div class="card mb-3"> 
      <% if @post.post_images.present? && @post.id.present? %>
        <p><%= User.find_by(id:(@post.user_id)).name %></p>
        <%= image_tag (@post.post_images.first.attachments.first  if @post.post_images.attached?) , style:" max-width: 100%;" %>
        <div class="mt-3">
          <p><%= @post.caption %></p>
            <div class="d-flex">
              <% if user_signed_in? %>
                <% if Like.where(user_id: current_user.id , likeable_id: @post.id ).present? %> 
                  <%= link_to "Unlike", post_like_path(post_id:@post.id , id:Like.find_by(user_id: current_user.id , likeable_id: @post.id ).id ) , class: "btn btn-outline-success btn-sm", style:"height:38px" , data: { turbo_method: :delete } %>
                  <div>
                    <%= render "posts/allLikes", post: @post %>
                  </div>
                <% else %>
                <%= form_with(url: post_likes_path(@post)) do %>
                <button class="btn btn-outline-success"> <%= Like %> </button>
              <% end %>
              <div>
                <%= render "posts/allLikes", post: @post %>
              </div>
              <% end %>
              <% end %> 
              <div>
                <%= link_to "Create Comment", new_post_comment_path(@post), class: "btn btn-outline-success ms-1" %>
              </div> 
              <div>
                <%=render "posts/allcomment" , post: @post %>
              </div> 
            </div>

            <div style="margin-left:93.5%">
              <%= link_to 'Back', show_user_path(@post.user_id), class:"btn btn-outline-success" %>
            </div>
            <% else %>
            <div class="form-group mt-4 , text-center">
            <%= form.submit 'Create Post', class: 'btn btn-dark' %>
            </div>
            <p>There is no post available</p>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>